### ISSUE TITLE
StopLoss and TakeProfit not implented?

### ISSUE THREAD

**Issue by Matx00** [ejtraderLabs/ejtraderCT#1]
Hi,
I love this idea. Really needed it!!!
Said that, is it normal that StopLoss and TakeProfit are not implented/don't work yet?
Is it also normal that only symbols with a string length of 6 can be traded?

Thank you

**Comment by traderpedroso** [comment]
> Hi,
> I love this idea. Really needed it!!!
> Said that, is it normal that StopLoss and TakeProfit are not implented/don't work yet?
> Is it also normal that only symbols with a string length of 6 can be traded?
> 
> Thank you

When you add limit / stop order you will be able to specify the existing position ID and the new order will be "linked" to the existing position. You won't see that on cTrader GUI but when the pending order get executed you are actually modifying the existing position. I think I'm displaying the linked ID on the order window.

we need help to implement a simple call through the ejtraderCT library if you have any suggestions do a fork and pull request thank you
