### ISSUE TITLE
STUKED WITHOUT RESPONSE

### ISSUE THREAD

**Issue by DiMiTriFrog** [ejtraderLabs/ejtraderCT#18]
I'm having no response when I'm running the **Ctrader** (from ejtraderCT import Ctrader). i tried to put a wrong password and the same...
Any suggestion?

**Comment by traderpedroso** [comment]
> I'm having no response when I'm running the **Ctrader** (from ejtraderCT import Ctrader). i tried to put a wrong password and the same...
> Any suggestion?

please share your code and log error

**Comment by Mubo-412** [comment]
Same here. No Logs are provided with debug logging. Here is where it is stuck:

File "/opt/miniconda3/lib/python3.8/site-packages/ejtraderCT/api/ctrader.py", line 48, in __init__
    self.fix = FIX(
  File "/opt/miniconda3/lib/python3.8/site-packages/ejtraderCT/api/fix.py", line 212, in __init__
    self.qs.connect((server, 5201))
KeyboardInterrupt

**Comment by DiMiTriFrog** [comment]
I'm using the example test:

from ejtraderCT import Ctrader
server="78.129.190.32" # - Host name: (Current IP address 168.205.95.20 can be changed without notice)
account="demo.icmarkets.MY_ACCOUNT" #  - SenderCompID: live.icmarkets.1104926
password="MY_Pswd" # - The password you configured

api = Ctrader(server,account,password)


print(api.isconnected())
