### ISSUE TITLE
hi, how can i confirm or find my  Forex broker's  'FIX_SERVER' address?

### ISSUE THREAD

**Issue by lxhxinyu** [ejtraderLabs/ejtraderCT#2]
FIX_SERVER="h8.p.c-trader.cn"
FIX_BROKER="icmarkets"
FIX_LOGIN="3152339"
FIX_PASSWORD="393214"
FIX_CURRENCY="EUR"

hi, how can i confirm or find my  Forex broker's  'FIX_SERVER' address? Thanks

**Comment by traderpedroso** [comment]
> FIX_SERVER="h8.p.c-trader.cn" FIX_BROKER="icmarkets" FIX_LOGIN="3152339" FIX_PASSWORD="393214" FIX_CURRENCY="EUR"
> 
> hi, how can i confirm or find my Forex broker's 'FIX_SERVER' address? Thanks

the server is on the same place you get API dates from ctrader
