### ISSUE TITLE
ASK: Why about modify positions?

### ISSUE THREAD

**Issue by DiMiTriFrog** [ejtraderLabs/ejtraderCT#23]
it's posible to implement smem function to modify the current position and change stoploss and take profit?
Like trailing stop

**Comment by traderpedroso** [comment]
> it's posible to implement smem function to modify the current position and change stoploss and take profit?
> Like trailing stop


In previous versions, we had the option to change 'stop', but the FIX API was not exactly designed for this, as described in the documentation, hence it wasn't reliable to maintain stability and functionality, so it was removed. The best option is for your code to send a cancellation request by order ID, as per the README documentation, or to cancel all if you're managing a single order per asset.


Given these limitations, you will need to construct your stop loss rules according to your requirements. We do not plan to reimplement this feature. If you require a system with full functionality, you won't be able to use the FIX API, but rather the REST API, in this case, the cTrader's Open API. The FIX API is really exclusive for high-frequency trading and instant execution, unlike the REST API, which is significantly slower.

**Comment by DiMiTriFrog** [comment]
Thanks for de clarify! You have realy good libs.
