### ISSUE TITLE
Can not reach server

### ISSUE THREAD

**Issue by qyqzeus** [ejtraderLabs/ejtraderCT#3]
When I use a live account：
![image](https://user-images.githubusercontent.com/34377498/146009132-07ee1187-8c10-4290-ab1f-236133e93b1b.png)

When I use a Demo account：
![image](https://user-images.githubusercontent.com/34377498/146008859-31d428ab-7d81-4a27-a301-47d018a74913.png)
 
Where is the problem with this prompt, thank you

**Comment by traderpedroso** [comment]
can you replicate you error
