### ISSUE TITLE
cant login,ERROR:root:Logged out: Can't route request

### ISSUE THREAD

**Issue by atreeyang** [ejtraderLabs/ejtraderCT#4]
"ERROR:root:Logged out: Can't route request
ERROR:root:Logged out: Can't route request
ERROR:root:Disconnected
ERROR:root:Disconnected"

FIX_SERVER="h51.p.ctrader.com"
FIX_BROKER="icmarkets"
FIX_LOGIN="8337657"
FIX_PASSWORD="KDCG2008"
FIX_CURRENCY="USD"

FIX API information from ctrader web:
"Host name: h51.p.ctrader.com
(Current IP address 176.58.118.184 can be changed without notice)
Port: 5211 (SSL), 5201 (Plain text).
Password: (a/c 8337657 password)
SenderCompID: demo.icmarkets.8337657
TargetCompID: CSERVER
SenderSubID: QUOTE

Host name: h51.p.ctrader.com
(Current IP address 176.58.118.184 can be changed without notice)
Port: 5212 (SSL), 5202 (Plain text).
Password: (a/c 8337657 password)
SenderCompID: demo.icmarkets.8337657
TargetCompID: CSERVER
SenderSubID: TRADE"

**Comment by traderpedroso** [comment]
> "ERROR:root:Logged out: Can't route request ERROR:root:Logged out: Can't route request ERROR:root:Disconnected ERROR:root:Disconnected"
> 
> FIX_SERVER="h51.p.ctrader.com" FIX_BROKER="icmarkets" FIX_LOGIN="8337657" FIX_PASSWORD="KDCG2008" FIX_CURRENCY="USD"
> 
> FIX API information from ctrader web: "Host name: h51.p.ctrader.com (Current IP address 176.58.118.184 can be changed without notice) Port: 5211 (SSL), 5201 (Plain text). Password: (a/c 8337657 password) SenderCompID: demo.icmarkets.8337657 TargetCompID: CSERVER SenderSubID: QUOTE
> 
> Host name: h51.p.ctrader.com (Current IP address 176.58.118.184 can be changed without notice) Port: 5212 (SSL), 5202 (Plain text). Password: (a/c 8337657 password) SenderCompID: demo.icmarkets.8337657 TargetCompID: CSERVER SenderSubID: TRADE"

bug for FIX_CURRENCY should use aways EUR doesn't make any diference if you are on USD currency should use EUR
