### ISSUE TITLE
AttributeError: 'Ctrader' object has no attribute 'api'

### ISSUE THREAD

**Issue by savasturkoglu1** [ejtraderLabs/ejtraderCT#5]
when i try get history with this method;
` history = api.history("GBPUSD", "H1", int(datetime.datetime.now().timestamp()) - 10000)`
i got error;
`AttributeError: 'Ctrader' object has no attribute 'api' `
 there is no api defination in the class

**Comment by traderpedroso** [comment]
tell me more about you envoriment python version its been tested only on python 3.7

`from ejtraderCT import Ctrader

FIX_SERVER="h8.p.c-trader.cn"
FIX_BROKER="icmarkets"
FIX_LOGIN="3152339"
FIX_PASSWORD="393214"
FIX_CURRENCY="EUR"

# api defined here
api = Ctrader(FIX_SERVER,FIX_BROKER,FIX_LOGIN,FIX_PASSWORD,FIX_CURRENCY)

api.buy("EURUSD", 0.01, 1.18, 1.19)

`

**Comment by traderpedroso** [comment]
> @traderpedroso ye I know that I can connect the server that way. But when i call history method so this Method in ctrader.py:
> 
> ```
> def history(self, symbol, chartTF, fromDate):
>         return json.loads(json.dumps(self.api.Command(action="HISTORY", actionType="DATA", symbol=symbol, chartTF=chartTF, fromDate=fromDate)))
> ```
> 
> i got this error
> 
> `AttributeError: 'Ctrader' object has no attribute 'api'`
> 
> coz there is no api defination in the class what mean -api- in ctrader.py ?

sorry for the late response ill try to fix it this weekend
